### ISSUE TITLE
off-topic

### ISSUE THREAD

**Issue by SparK-Cruz** [Yethiel/re-make#1]
Hey Yethiel,
Sorry for opening an issue but github has no messaging system :P

Do you know where I can find the developer of RV House or the project so I can build it for 64bit arch linux? Damn thing was 32 bit only and lib32/libACE is nowhere to be seen in AUR or google for that matter...

Anyway keep up the great work, I always check the trello board to see if something is being planned or if the project is moving.

**Comment by Yethiel** [comment]
You can find it on huki's GitHub: https://github.com/gk7huki/rvhouse
